### ISSUE TITLE
Quarto config file is changed by nbdev_docs

### ISSUE THREAD

**Issue by liquidcarbon** [fastai/nbdev#1020]
I edited `_quarto.yml` file to change a CSS theme:

```
format:
  html:
    page-layout: article
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4
```

Ran `nbdev_docs` and `_quarto.yml` was reverted to the original state:
```
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
```

Apologies if I overlooked an obvious setting that drives this behavior.  Otherwise, seems like this should not be happening.

Thanks!

## System
```
In [3]: nbdev.__version__
Out[3]: '2.3.0'
```
```
quarto check

[✓] Checking Quarto installation......OK
      Version: 1.1.189
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
```
