### ISSUE TITLE
How to guide for running prerelease library versions

### ISSUE THREAD

**Issue by tylere** [fastai/nbdev#1021]
_aka "runs with scissors"_

Document how to develop and test with pre-release versions of nbdev and the primary dependencies (i.e. quarto, jupyter), all of which are actively being developed. 

Some topics to potentially include:

- Describe how to preview locally using a prerelease version of nbdev (head or a particular commit)

  For example:
  ```
  pip install -U git+https://github.com/fastai/nbdev.git@08462b3da90c86a06cd62159babc69c346d21f88
  ```

- Describe how to deploy to GitHub using a prerelease version of nbdev and/or quarto

   workflows/deploy.yaml
  ```
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: fastai/workflows/quarto-ghp@master
          with: {pre: 1}
  ```
