### ISSUE TITLE
Why not delegate publishing completely to quarto publishing framework?

### ISSUE THREAD

**Issue by Rahuketu86** [fastai/nbdev#1066]
Version 2.3.0 

**Request for enhancement**

**_Why not delegate publishing completely to quarto publishing framework?_**

With the introduction of _proc in version 2.3.0 , nbdev resolves a few issues around publishing. But it still doesn't completely capitalize _quarto publishing functionality. 

Let me try to explain 
When I run the nbdev_preview command a _docs folder is generated in the _proc directory. Looking at the source code I believe same/similar _docs folder is generated by the nbdev_docs command at the root directory. 

My thought process is following 
1. Generate a _publish.yml in _proc folder using the quarto publish command.
2. We can still use the nbdev_docs command but this _proc/_docs folder is updated with everything expected in terms of rendering ( without prior cache etc...)
3. Modify deploy action at https://github.com/fastai/workflows/blob/master/quarto-ghp/action.yml to something more general which (a) runs nbdev_docs (b) uses something similar to quarto publish action to deploy the docs based on _publish setting.
(In fact, default deployment to GitHub pages can be already configured for _publish.yml while generating _proc folder using nbdev_prepare but can be modified by a user on demand based on a case-by-case basis.)

The below setup for deploy has not worked ( might be an issue with quarto-action) - with various combinations of path[ _proc, ./_proc] or putting _publish.yml in multiple places ( _proc dir, root dir, both, etc..)
Note : - I can run quarto publish netlify locally (it's just that quarto action is failing for some reason)

```
name: CI
on:
  push:
    paths-ignore:
      - 'book/**'
      - 'nbs_pluto/**'
      - 'nbs_pluto_html/**'
      - 'devops/**'
  pull_request:
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Dependencies
      run: |
        sudo apt install -y graphviz

    - name: Fastai CI
      uses: fastai/workflows/nbdev-ci@master

    - name: Run nbdev_docs
      shell: bash
      run: |
        nbdev_docs

    - name: Render and Publish 
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: netlify
        path: _proc
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
```

Failing with following message :- 

`No _publish.yml file available (_publish.yml specifying a destination required for non-interactive publish)`

I am using the following to achieve netlify deployment which solves what I want to achieve for now. However, it would be much better if we can link to publishing framework directly from quarto. This way it would be easier to adapt actions once they move to a profile system (See my issue in quarto-actions https://github.com/quarto-dev/quarto-actions/issues/44#issue-1370052669)
```

name: CI
on:
  push:
    paths-ignore:
      - 'book/**'
      - 'nbs_pluto/**'
      - 'nbs_pluto_html/**'
      - 'devops/**'
  pull_request:
  workflow_dispatch:


jobs:
  test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Dependencies
      run: |
        sudo apt install -y graphviz

    - name: Fastai CI
      uses: fastai/workflows/nbdev-ci@master

    - name: Run nbdev_docs
      shell: bash
      run: |
        nbdev_docs

    - name: Push to netlify site
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './_docs'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1

```

_Originally posted by @Rahuketu86 in https://github.com/fastai/nbdev/issues/998#issuecomment-1246499695_
