### ISSUE TITLE
Enhancement for hooks

### ISSUE THREAD

**Issue by johnnv1** [fastai/nbdev#1175]
### Motivation
Improve integration with pre-commit

### Expected behavior
Can use the nbdev_clear without having a `nbdev` config at `settings.ini` or to implicit pass `args: ['-fname', 'mydir/']` at pre-commit config.

### Explanation
As I explain [here](https://github.com/fastai/nbdev/issues/1152#issuecomment-1288105205), seems to be a workaround need to add the `path` if you don't have a nbdev config. Mainly, because this will cause the command to be executed for all files at that path, which is unnecessary.

If the command accepts `n` arguments (multiple filenames), we can use the pre-commit "normally", by letting it command in which files the hook should be executed -- only those that have been changed in the commit.

Consequently, this will improve the hook's execution speed, since it will not be checking for unnecessary files.

----

With this enhancement, we can update the `.pre-commit-hooks.yaml` to:

```diff
--- a/.pre-commit-hooks.yaml
+++ b/.pre-commit-hooks.yaml
@@ -5,7 +5,8 @@
   always_run: true
-  pass_filenames: false
+  pass_filenames: true
+  types: [jupyter]
```

**Comment by seeM** [comment]
Good idea! `nbdev_clean` currently doesn't take any positional arguments so we could make the change so that it optionally takes a list of files

**Comment by dijonkitchen** [comment]
I think similarly, it'd be good to have other pre-commit behavior like only including certain filetypes or excluding files. Currently, `nbdev` runs on everything and may be using more time than it needs. 

Example:
```yaml
repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.3.11
    hooks:
      - id: nbdev_clean
        files: \.ipynb$ # This doesn't work for `nbdev` but does for other pre-commit hook plugins. 
```

If it works properly, when the pre-commit hook runs, it should say "Skipped" if no `.ipynb` files were changed.
