### ISSUE TITLE
Add path to be cleaned by hook outside `nbs/`

### ISSUE THREAD

**Issue by yasirroni** [fastai/nbdev#1187]
Looking at the code below,  https://github.com/fastai/nbdev/blob/656b7bc26c8760f839a6106250f071e8e096397c/nbdev/clean.py#L139 it seems that `nbdev` hook only clean notebook inside `nbs`.

How to include other folder?

Maybe support the notation in the `pre-commit`?

Something like..

```
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
    - id: nbdev_clean
      include: ^other_than_nbs/*.ipynb
    - id: nbdev_export
```
