### ISSUE TITLE
Sidebar not showing on pages deployment

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#1305]
# Provide a minimally reproducible example

I have another issue (see here: https://github.com/fastai/nbdev/issues/1279) and have changed my workflow files accordingly.
I ran `nbdev_prepare` and `nbdev_preview` and `nbdev_docs` all ran successful (and locally I see all the pages and the sidebar).
Only on GitHub I dont.

If we are not able to reproduce your error, we may close your issue.

**Comment by deven-gqc** [comment]
Just want to make sure, you have also pushed the `sidebar.yml` file to the repo?

**Comment by deven-gqc** [comment]
> Default .gitignore file and the sidebar is there

I'm not sure if I understand the last statement. If your `gitignore` file has `sidebar.yml` remove it, and then push the file. 

You can look at this minimal [repo](https://github.com/deven367/nbdev-oauth) to see the setup of `_quarto.yml`, `sidebar.yml` and `nbdev.yml`

**Comment by dsm-72** [comment]
@deven-gqc I made a new nbdev project so it has the default .gitignore file i.e. sidebar.yml, _quarto.yml etc are all **in** the repo.

**Comment by deven-gqc** [comment]
Can you please a small reproduction example for this? I'm not sure if your issue might be related to #1300

**Comment by dsm-72** [comment]
@deven-gqc  I made a new private nbdev repo, copy-pasta 00_core a few times, set up the import and pages and previews ok, but no luck on deployment for GitHub

**Comment by dsm-72** [comment]
@deven-gqc 

I changed by deploy.yaml from
```
name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: '3.10'

```
to
```
name: Deploy to GitHub Pages
on:  [workflow_dispatch, pull_request, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/quarto-ghp@master
        with:
          version: '3.10'
```

```
Push the commit or tag
[661](https://github.com/dsm-72/degex/actions/runs/4307207983/jobs/7511993656#step:2:679)
  /usr/bin/git push origin --force gh-pages
[662](https://github.com/dsm-72/degex/actions/runs/4307207983/jobs/7511993656#step:2:680)
  remote: Write access to repository not granted.
[663](https://github.com/dsm-72/degex/actions/runs/4307207983/jobs/7511993656#step:2:681)
  fatal: unable to access 'https://github.com/dsm-72/degex.git/': The requested URL returned error: 403
[664](https://github.com/dsm-72/degex/actions/runs/4307207983/jobs/7511993656#step:2:682)
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```
