### ISSUE TITLE
`nbdev_new` fails due to uncleaned notebooks

### ISSUE THREAD

**Issue by dsm-72** [fastai/nbdev#1311]
```
no changes added to commit (use "git add" and/or "git commit -a")
[521](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:533)
!!! Detected unstripped out notebooks
[522](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:534)
!!!Remember to run nbdev_install_hooks
[523](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:535)
+ echo -e '!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks'
[524](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:536)
+ false
[525](https://github.com/USER/REPO/actions/runs/4398996689/jobs/7703235848#step:2:537)
Error: Process completed with exit code 1.
```

**Comment by dsm-72** [comment]
I also have `pre-commit-hooks` installed and they _succeed_:

```yml
repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
  - id: nbdev_export
 ```

so why would these pass and GitHub fail?
