### ISSUE TITLE
Default sidebar links broken

### ISSUE THREAD

**Issue by omlnaut** [fastai/nbdev#219]
Issue:
The links in a newly generated "default sidebar" point to <notebook_name>.html
Since "pretty links" are the default for the jekyll page generation, this does not work (404 on following the link from the index page).

Steps to reproduce:
1. Generate a new project via the template, enable github pages
2. Build lib, build docs, push to github
3. Access the generated documentation on github, try to click the link to the core notebook

Possible fixes:
The breaking commit seems to be da400c3572a944e23d569a6017bc0884335e1d36 (20.08.). It replaced "f.stem" by "f.name", therefore making it "core.html" instead of "core". I don't know why this change was made, so one fix would be to:

1. Undo this particular change (not sure what this would break further down the line)
or
2. Turn of jekyll "pretty links" in the _config.yml.

UPDATE:
I just realized that in the same commit Jeremy changed the _config.yml for the nbdev documentation to essentially implement solution 2 from above. If this is intended to be the solution then we should adjust the nbdev template to generate such a _config.yml by default. I would prefer this solution, as it allows to have the documentation generated in a static way that doesn't require a running jekyll server to view it.

**Comment by koenvanderveen** [comment]
I think I have a similar issue. I have a repo called "integrators" and a nb that exports to basic.py. My navigation has an item called "title" and when I click it, it says: `/integratorsbasic.html' not found.

**Comment by simonasantamaria** [comment]
Thanks, your suggestion "2. Turn of jekyll "pretty links" in the _config.yml." worked for me!

**Comment by coffeedjimmy** [comment]
It works for me either! 

please erase out if there is "pretty links" in the _config.yml file.

**Comment by koenvanderveen** [comment]
that does not solve it for me. I am using the gitlab template from https://gitlab.com/thomas.capelle/nbdev_template/. By "pretty links" you mean the "permalink: pretty" line?

**Comment by koenvanderveen** [comment]
If I am manually chaning that f.name to f.stem, I am still missing the slash. Any idea where that should be added?

**Comment by omlnaut** [comment]
> If I am manually chaning that f.name to f.stem, I am still missing the slash. Any idea where that should be added?

Without looking at your config I don't know what's causing this.

**Comment by koenvanderveen** [comment]
My config looks like this

```
repository: https://gitlab.memri.io/memri/pyintegrators
output: web
topnav_title: integrators
site_title: memri integrators
company_name: memri
description: memri integrators, integrating your information
# Set to false to disable KaTeX math
use_math: true
# Add Google analytics id if you have one and want to use it here
google_analytics:
# See http://nbdev.fast.ai/search for help with adding Search
google_search:

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor
 
exclude: [vendor]

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars:
- home_sidebar

theme: jekyll-theme-cayman
baseurl: /integrators
permalink: pretty
```
