### ISSUE TITLE
Tutorial issue: Build failure due to python version

### ISSUE THREAD

**Issue by hamzahiqb** [fastai/nbdev#374]
I keep getting the following error:

`ERROR: Package 'nbdev-test' requires a different Python: 3.6.12 not in '<4.0,>=3.8'`

The build logs can be found here: https://github.com/hiqbal2/nbdev_test/actions/runs/481370649

Not sure what I am doing wrong but I have the entire repo saved. The only difference I have is that I am using poetry for environment management and use python 3.8 on Mac Mojave (10.14.6).

**Comment by hamelsmu** [comment]
Can you outline the exact steps that led to this error, when I follow the tutorial I'm not able to reproduce.  I'm happy to open this issue back up if you can outline the steps necessary to reproduce this error.

**Comment by hoangthienan95** [comment]
@hamzahiqb @hamelsmu I ran into this problem. To anyone who uses poetry for dependency management and reading this, here are the steps to resolve:

1. edit `.github/workflows`, setup-python step to: 

```yaml
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8' #or whatever version your system/pyenv is using
        architecture: 'x64'
```

2. Comment out the `Install the library step`

3.  Add the following steps to install poetry and project dependencies. You can read more about them and about the caching feature from [this link](https://medium.com/@vanflymen/blazing-fast-ci-with-github-actions-poetry-black-and-pytest-9e74299dd4a5) although at the time of writing, their `install poetry` and `poetry config` steps was outdated so I replaced with a new one.

```yaml
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.4 #you can add your own version or a matrix of versions here

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
```

4. add `poetry run` before the `nbdev_read_nbs` and `nbdev_test_nbs` commands

You can see a complete example of the `main.yml` file I used [here](https://github.com/hoangthienan95/nbdev_tutorial_2nd_try/blob/master/.github/workflows/main.yml)
