### ISSUE TITLE
use conda environment in GitHub action

### ISSUE THREAD

**Issue by sunhwan** [fastai/nbdev#414]
I have a requirement that can only be installed by conda. Is there a way to use conda environment in GitHub action instead of pip?

**Comment by sunhwan** [comment]
I'm not sure if this package provides any method to do this automatically, but I was able to use conda environment instead of pip only by editing the `.github/workflow/main.yml` file directly.

Below is my edit:

```
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: 3.6
        channels: rdkit
    - name: Install the library
      run: |
        pip install nbdev jupyter
        conda install [your package]
```

See also: https://github.com/marketplace/actions/setup-miniconda
