### ISSUE TITLE
ignore subfolder when running build_docs

### ISSUE THREAD

**Issue by esillekens** [fastai/nbdev#499]
The virtualenv for the project is located in the folder, but when the nbdev_build_docs is run, it finds all kind of notebooks to make docs out of. 

Is there a place I can tell nbdev where my virtualenv is located or exclude it from documentation generation another way?

**Comment by jph00** [comment]
Should be fixed in v2

**Comment by VehpuS** [comment]
I still have issues with v2.1.3 - my `sidebar.yml` is generated with the following:
```yaml
website:
  sidebar:
    contents:
      - index.ipynb
      - 00_core.ipynb
                                  - section: dir
                                    contents:
                                      - dev-env/lib/python3.9/site-packages/tornado/test/static/dir/index.html
                              - section: templates
                                contents:
                                  - dev-env/lib/python3.9/site-packages/tornado/test/templates/utf8.html
```
