### ISSUE TITLE
CI fails on missing requirements

### ISSUE THREAD

**Issue by dellaert** [fastai/nbdev#572]
Thanks for this amazing tool!

The CI workflow specified in `main.yml` file does not work properly if there are dependencies specified in `settings.ini,` and it's not super-easy to get this working if there are `conda_requirements` specified. I was able to work around this by having an `environment.yml` file and using a custom action [here](https://github.com/gtbook/gtbook/blob/master/.github/workflows/main.yml), relevant bits being:

```yaml
    - name: Activate conda env with environment.yml
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        auto-activate-base: false
        activate-environment: gtbook-dev
        python-version: 3.8
        environment-file: etc/environment.yml
    - name: Install the library
      run: pip install -e .
```
and, crucially, to ensure this action works properly:
```yaml
    defaults:
      run:
        shell: bash -l {0}
```
The last bit took me a while to find out, by finally [rtfm](https://github.com/conda-incubator/setup-miniconda#important).

It would be nice if this file was built automatically from `settings.ini`, or (even better?) if dependencies were simply done using a standard `environment.yml` file, in which case the above would cover both conda and pip install requirements.

In any case, maybe this issue (and #414) might be of help to anyone else facing this.
