### ISSUE TITLE
`nbdev_preview` not starting if there is a folder with no notebook in it

### ISSUE THREAD

**Issue by jerzydziewierz** [fastai/nbdev#922]
**Environment**
* Create a new folder, and a subfolder For example, /folder1/folder2
* Create a new notebook in /folder1/folder2/aNotebook.ipynb
* in the command line, from the root folder, issue 'nbdev_preview`

**Observed behaviour**
```bash
ERROR: 
Error reading metadata file from /sidebar.yml

ERROR: YAMLException: bad indentation of a sequence entry (sidebar.yml, 6:20)
5:       - 00_core.ipynb
6:           - section: afolder2
                      ~
7:             contents:

```

**Expected behaviour**

`nbdev_preview` should start as normal.

**Suggested source of the problem**

in `sidebar.yml` (partial)
```yaml
website:
  sidebar:
    contents:
      - index.ipynb
      - 00_core.ipynb
          - section: afolder2  ::: NOTE DOUBLE INDENT HERE
            contents:
              - afolder1/afolder2/aNotebook.ipynb
```

Yaml does not like if there is no content directly in a section, and gets thrown off if there is a double indentation instead.

This might be a YAML limitation, and a workaround is needed. 

**Suggested workaround 1**

Add an empty notebook into that empty folder?

**Suggested workaround 2**

Add a meaningful error message and instructions for the user what to do?
